version: 2.1
orbs:
  matlab: mathworks/matlab@0.3.0
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    parameters:
      version:
        description: "MATLAB version"
        default: "R2020b"
        type: string
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install:
          release: <<parameters.version>>
      - matlab/run-tests:
          test-results-junit: artifacts/junit/testResults.xml
          code-coverage-cobertura: artifacts/coverage/codeCoverage.xml
          source-folder: code
      - store_test_results:
          path: artifacts/junit
      - store_artifacts: 
          path: artifacts
      - codecov/upload:
          file: artifacts/coverage/codeCoverage.xml
          
  start-simulink:
    parameters:
      version:
        description: "MATLAB version"
        default: "R2020b"
        type: string
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install:
          release: <<parameters.version>>
      - matlab/run-command:
          command: disp('matlab started'); start_simulink; disp('simulink started')
      - matlab/run-command:
          command: disp('matlab started (round 2)'); start_simulink; disp('simulink started (round 2)')


workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - R2020a
                - R2020b
                - R2021a
      - start-simulink:
          matrix:
            parameters:
              version:
                - R2020a
                - R2020b
                - R2021a
