version: 2.1
orbs:
  matlab: mathworks/matlab@0.2
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: artifacts/junit/testResults.xml
          code-coverage-cobertura: artifacts/coverage/codeCoverage.xml
          source-folder: code
      - store_test_results:
          path: artifacts/junit
      - store_artifacts: 
          path: artifacts
      - codecov/upload:
          file: artifacts/coverage/codeCoverage.xml