# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
          
  validate-code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0

      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-command@v0
        with:
          command: runAllTests
          
      - name: Publish Results 🚀
        if: ${{ always() }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: false # 
          CLEAN_EXCLUDE: '["dev", "jobs"]'
     # - name: Create public index
      #  run: |
       #   echo '<!DOCTYPE html>' >> public/index.html
        #  echo '<html>' >> public/index.html
         # echo '  <head>' >> public/index.html
          #echo '    <title>Job Results</title>' >> public/index.html
#          echo '  </head>' >> public/index.html
 #         echo '  <body>' >> public/index.html
  #        echo '    <p><a href="test-results/index.html">Test Results</a></p>' >> public/index.html
   #       echo '    <p><a href="code-coverage/index.html">Code Coverage</a></p>' >> public/index.html
    #      echo '    <p><a href="dev/bench/index.html">Performance Results</a></p>' >> public/index.html
     #     echo '  </body>' >> public/index.html
      #    echo '</html>' >> public/index.html
  assess-performance:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0
        
      - name: Run performance tests
        uses: matlab-actions/run-command@v0
        with:
          command: runPerfTests

      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result (cpp format)
        uses: rhysd/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'googlecpp'
          output-file-path: cpp-benchmark-data.json
          #fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-comment-cc-users: '@acampbel'

      - name: Store benchmark result (pytest format)
        uses: rhysd/github-action-benchmark@v1
        with:  
          # What benchmark tool the output.txt came from
          tool: 'pytest'
          output-file-path: py-benchmark-data.json
          #fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-comment-cc-users: '@acampbel'
  
  build-results-site:
    runs-on: ubuntu-latest
    needs: [assess-performance,  validate-code]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install tree
        run: sudo apt install tree

      - name: Look around
        run: tree
        
      - name: Create top level index
        run: tree -d -L 1 -H '.' -T 'Job Results' --noreport --charset utf-8 > index.html
    
      - name: Create the benchmarking index
        run: cd dev ; tree -d -L 1 -H '.' -T Benchmarks --noreport --charset utf-8 > index.html
        
      - name: Create jobs index
        run: cd jobs ; tree -d -t -L 1 -H '.' -T Jobs --noreport --charset utf-8 > index.html
        
      - name: Create this jobs index
        run: cd jobs/$GITHUB_RUN_NUMBER ; tree -d -L 1 -H '.' -T "Job $GITHUB_RUN_NUMBER"  --noreport --charset utf-8 > index.html


      - name: Publish to pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: gh-pages
          CLEAN: false # 
          PRESERVE: true
          CLEAN_EXCLUDE: '["dev", "jobs"]'
          
